server:
  port: 8081
  servlet:
    context-path: /videoDownload

video-download:
  folder: D:\video-download\video
  ffmpegPath: D:\SDK\ffmpeg-master-latest-win64-gpl\bin\ffmpeg

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    #    data-username: videoDownload
#    #    data-password: videoDownloadPassword@123
#    schema: DB/schema.sql
#    data: DB/data.sql
#    platform: m2
#
#  h2:
#    console:
#      path: /h2-console
#      enabled: true

spring:
  datasource:
    username: root
    password: 123456
    #  驱动
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    #    # h2 内存数据库 内存模式连接配置 库名: mybatis
    #    url: jdbc:h2:mem:testdb
    # 初始化数据表 DDL
  #    schema: classpath:sql/init.sql
  #    #  初始化数据 DML
  #    data: classpath:sql/data.sql
  h2:
    #    开启console 访问 默认false
    console:
      enabled: true
      settings:
        #      开启h2 console 跟踪 方便调试  默认 false
        trace: true
        #      允许console 远程访问 默认false
        web-allow-others: true
      #  h2 访问路径上下文
      path: /h2-console
